[server]
headless = true
enableCORS = false
enableXsrfProtection = false

[browser]
gatherUsageStats = false

[theme]
base="dark"
primaryColor="#ef4444"
backgroundColor="#181818"
secondaryBackgroundColor="#232323"
textColor="#fafafa"
font="sans serif" 